### ISSUE TITLE
add more comments to ModelSelector. 

### ISSUE THREAD

**Issue by dunlingliyang** [jyhong836/MatExManager#2]
I think the overall procedure is fairly easy to understand. The only modification i think will be including more comments on the `modelselector.m`, because this file contails many odd parametric names and settings.  further suggestions will be submitted when i am trying to tinker with them

**Comment by jyhong836** [comment]
@dunlingliyang Hey, bro! Check out the newest updates. I have added some comments.

**Comment by dunlingliyang** [comment]
you set several global variables which makes the code unable to run properly. 

new updates is fine to me， at least I can read through all the codes without much hindrance.
